version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config', '/conf/otel-collector-config.yml']
    ports:
      - '4317:4317'
    volumes:
      - ./config/otel-collector-config.yml:/conf/otel-collector-config.yml:ro
    networks:
      - monitoring
      - soa_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686' # UI
      - '14250:14250' # gRPC (collector)
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    ports:
      - '3100:3100'
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    pid: 'host'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8089:8080'
    networks:
      - monitoring

  observability-service:
    build: ./apps/observability-service
    ports:
      - '8001:8001'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
  soa_network:
    external: true
    name: soa-projekat_soa_network
