ALTER TABLE profiles
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN surname SET NOT NULL,
ALTER COLUMN image_url SET NOT NULL,
ALTER COLUMN biography SET NOT NULL,
ALTER COLUMN moto SET NOT NULL;

ALTER TABLE profiles
DROP CONSTRAINT profiles_user_id_fkey,
DROP COLUMN user_id;
